### PR TITLE
feat(state): add none state mapping

### PR DESCRIPTION
**Pull request by SkeLLLa**
This is some initial PR for #145 .

If it's fine from card logic and I didn't miss anything, I can proceed with adding relevant docs.

### CODE REVIEW

**Comment by dylandoamaral** [comment]
Nice feature did you try it in dev ?

**Comment by SkeLLLa** [comment]
Now checked it and looks like it works fine. Icon and state is mapped to unknown. Other cards that were in demo work fine.

**Comment by dylandoamaral** [comment]
Thank you for the PR !

**Comment by SkeLLLa** [comment]
Updated. I consider that the next version will be `1.4.0`, if not, then you'll need to set proper one next to new fields table.

**Comment by SkeLLLa** [comment]
image
Checked new version published, works fine for me.

**Pull request merged**
