### PR TITLE
Update uptime-card.ts

### PR DESCRIPTION
**Pull request by jokob-sk**
Add support for input_boolean as binary entity

### CODE REVIEW

**Comment by jokob-sk** [comment]
Hope this works - couldn't figure out how to test this - haven't done docker development before, but looking thru the code it should

**Comment by dylandoamaral** [comment]
Thank you for your pull request !

**Comment by dylandoamaral** [comment]
The CI/CD block, you should run the command `npm run format`

**Comment by jokob-sk** [comment]
alright, did it, hope it's ok now :)

**Comment by jokob-sk** [comment]
hey, just checking in if you want me to do fix something on this PR as some checks failed?

**Comment by dylandoamaral** [comment]
I am sorry, I was in holiday ! I will check why the HACS CI block today and hopefully make a release with your fix.

**Comment by jokob-sk** [comment]
Hey, no need to say sorry, was just worried something is waiting for my input. Hope you had a great holiday and don't take PR's and FOSS projects too seriously. Thanks for including my PR!

**Pull request merged**
